// src/lib/wordpress.ts
// Updated for WPGraphQL for maximum performance on Vercel SSR

const WP_BASE_URL = import.meta.env.PUBLIC_WP_BASE_URL || "https://dashboard.iraspa.in";
// Pointing to the new GraphQL endpoint generated by the plugin
const WP_GRAPHQL_URL = `${WP_BASE_URL}/graphql`;

export const POSTS_PER_PAGE = 9;
const FALLBACK_IMAGE = "/images/spa-treatment.jpg";

// --- TYPESCRIPT INTERFACES ---
export interface WPTerm {
	id: number;
	name: string;
	slug: string;
	taxonomy: string;
}

export interface WPPost {
	id: number;
	slug: string;
	date: string;
	modified: string;
	title: { rendered: string };
	excerpt: { rendered: string };
	content: { rendered: string };
	_embedded?: {
		author?: { name: string }[];
		"wp:featuredmedia"?: { source_url: string; alt_text: string }[];
		"wp:term"?: WPTerm[][];
	};
}

// --- CORE GRAPHQL FETCHER ---
async function fetchGraphQL(query: string, variables = {}) {
	try {
		const res = await fetch(WP_GRAPHQL_URL, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			// CRITICAL FIX: Bypass Vercel's aggressive fetch caching
			cache: "no-store", 
			body: JSON.stringify({ query, variables }),
		});

		if (!res.ok) {
			console.error(`[graphql] Responded with ${res.status}`);
			return null;
		}
		
		const json = await res.json();
		if (json.errors) {
			console.error("[graphql] Errors:", json.errors);
			return null;
		}
		return json.data;
	} catch (err) {
		console.error("[graphql] Network Error:", err);
		return null;
	}
}

// --- FETCH FUNCTIONS ---

export async function getAllPosts(): Promise<WPPost[]> {
	const query = `
		query AllPosts {
			posts(first: 100, where: { orderby: { field: DATE, order: DESC } }) {
				nodes {
					databaseId
					slug
					date
					modified
					title
					excerpt
					content
					author { node { name } }
					featuredImage { node { sourceUrl altText } }
					categories { nodes { databaseId name slug } }
				}
			}
		}
	`;

	const data = await fetchGraphQL(query);
	if (!data?.posts?.nodes) return [];

	// Map the GraphQL response back to the REST shape so your .astro files don't break
	return data.posts.nodes.map((node: any) => ({
		id: node.databaseId,
		slug: node.slug,
		date: node.date,
		modified: node.modified,
		title: { rendered: node.title },
		excerpt: { rendered: node.excerpt },
		content: { rendered: node.content },
		_embedded: {
			author: [{ name: node.author?.node?.name || "Ira Spa Team" }],
			"wp:featuredmedia": [{
				source_url: node.featuredImage?.node?.sourceUrl || FALLBACK_IMAGE,
				alt_text: node.featuredImage?.node?.altText || node.title
			}],
			"wp:term": [
				node.categories?.nodes?.map((cat: any) => ({
					id: cat.databaseId,
					name: cat.name,
					slug: cat.slug,
					taxonomy: "category"
				})) || []
			]
		}
	}));
}

export async function getPostBySlug(slug: string): Promise<WPPost | null> {
	const query = `
		query SinglePost($slug: ID!) {
			post(id: $slug, idType: SLUG) {
				databaseId
				slug
				date
				modified
				title
				excerpt
				content
				author { node { name } }
				featuredImage { node { sourceUrl altText } }
				categories { nodes { databaseId name slug } }
			}
		}
	`;

	const data = await fetchGraphQL(query, { slug });
	if (!data?.post) return null;

	const node = data.post;
	
	// Map the single GraphQL response back to your REST shape
	return {
		id: node.databaseId,
		slug: node.slug,
		date: node.date,
		modified: node.modified,
		title: { rendered: node.title },
		excerpt: { rendered: node.excerpt },
		content: { rendered: node.content },
		_embedded: {
			author: [{ name: node.author?.node?.name || "Ira Spa Team" }],
			"wp:featuredmedia": [{
				source_url: node.featuredImage?.node?.sourceUrl || FALLBACK_IMAGE,
				alt_text: node.featuredImage?.node?.altText || node.title
			}],
			"wp:term": [
				node.categories?.nodes?.map((cat: any) => ({
					id: cat.databaseId,
					name: cat.name,
					slug: cat.slug,
					taxonomy: "category"
				})) || []
			]
		}
	};
}

export async function getCategories(): Promise<WPTerm[]> {
	const query = `
		query AllCategories {
			categories(first: 100, where: { hideEmpty: true }) {
				nodes {
					databaseId
					name
					slug
				}
			}
		}
	`;

	const data = await fetchGraphQL(query);
	if (!data?.categories?.nodes) return [];

	return data.categories.nodes
		.map((node: any) => ({
			id: node.databaseId,
			name: node.name,
			slug: node.slug,
			taxonomy: "category"
		}))
		.filter((c: WPTerm) => c.slug !== "uncategorized");
}

// --- HELPER UTILITIES (Unchanged to maintain compatibility) ---

export function getFeaturedImage(post: WPPost): { src: string; alt: string } {
	const media = post._embedded?.["wp:featuredmedia"]?.[0];
	return {
		src: media?.source_url || FALLBACK_IMAGE,
		alt: media?.alt_text || stripHtml(post.title.rendered),
	};
}

export function getAuthorName(post: WPPost): string {
	return post._embedded?.author?.[0]?.name || "Ira Spa Team";
}

export function getPostCategories(post: WPPost): WPTerm[] {
	const termGroups = post._embedded?.["wp:term"] || [];
	return termGroups.flat().filter((t) => t.taxonomy === "category" && t.slug !== "uncategorized");
}

export function stripHtml(html: string): string {
	if (!html) return "";
	return html
		.replace(/<[^>]*>/g, " ")
		.replace(/&hellip;/g, "…")
		.replace(/&amp;/g, "&")
		.replace(/&#8217;|&#039;/g, "'")
		.replace(/&#8216;/g, "'")
		.replace(/&#8220;|&#8221;/g, '"')
		.replace(/&nbsp;/g, " ")
		.replace(/\s+/g, " ")
		.trim();
}

export function estimateReadTime(html: string): string {
	if (!html) return "1 min read";
	const words = stripHtml(html).split(" ").filter(Boolean).length;
	const minutes = Math.max(1, Math.round(words / 200));
	return `${minutes} min read`;
}

export function formatDate(dateString: string): string {
	if (!dateString) return "";
	return new Date(dateString).toLocaleDateString("en-IN", {
		year: "numeric",
		month: "long",
		day: "numeric",
	});
}